'use strict';
const $=s=>document.querySelector(s), key='dragon-radar-v1';
const defaults={name:'Explorer',theme:'classic',skin:'#c98c60',hair:'#473129',outfit:'#16706b',crown:false,quests:[],den:[],active:null,trail:['','','','','','']};
let state;try{state={...defaults,...JSON.parse(localStorage.getItem(key)||'{}')}}catch{state=structuredClone(defaults)}
let screen='home',question=0,editor=null,busy=false;
const templates=[{name:'Clean my room',steps:['Put dirty clothes in the hamper','Put toys in their homes','Put books where they belong','Clear one small section of the floor']},{name:'Tidy the bathroom',steps:['Put your things where they belong','Put dirty towels in the hamper','Wipe the counter with a grown-up’s help']},{name:'Backyard rescue',steps:['Collect outdoor toys','Put balls and games away','Pick up litter with a grown-up’s help']}];
const dragons=[{name:'Brickback',color:'#69a982',horn:'#f3c65d'},{name:'Sockjaw',color:'#a38bcc',horn:'#efd5a0'},{name:'Crumbclaw',color:'#ef9473',horn:'#ffe3a5'},{name:'Clutter King',color:'#567da4',horn:'#f7c658'}];
const prompts=['What treasure are you looking for?','When do you last remember having it?','Where were you?','What were you doing?','What did you do or where did you go next?','Do you remember putting it down or someone moving it?'];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>`<i data-lucide="${n}"></i>`;
const btn=(label,action,cls='',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
function save(){try{localStorage.setItem(key,JSON.stringify(state));return true}catch{toast('This browser could not save. Please free some storage before continuing.');return false}}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4000)}
function avatar(){return `<svg class="avatar" viewBox="0 0 160 180" role="img" aria-label="Your explorer"><circle cx="80" cy="88" r="72" fill="white" opacity=".5"/><path d="M25 173q0-63 55-63t55 63" fill="${state.outfit}"/><path d="M69 107h22v25H69" fill="${state.skin}"/><ellipse cx="80" cy="73" rx="36" ry="44" fill="${state.skin}"/><path d="M42 74V49q0-35 39-35t39 35v23l-16-22q-37 12-48-1Z" fill="${state.hair}"/><circle cx="67" cy="75" r="3" fill="#292b34"/><circle cx="94" cy="75" r="3" fill="#292b34"/><path d="M68 92q12 12 24 0" fill="none" stroke="#713f39" stroke-width="3" stroke-linecap="round"/><path d="m58 140 22 18 22-18" fill="none" stroke="#f5c75c" stroke-width="6"/>${state.crown?'<path d="m47 33 2-23 18 12 13-20 13 20 18-12 2 23Z" fill="#f5c75c"/>':''}</svg>`}
function dragon(n=0,cls=''){const d=dragons[n%4];return `<svg class="dragon ${cls}" viewBox="0 0 300 260" role="img" aria-label="${d.name}, a friendly chore dragon"><path d="m80 123-55-68-8 107 55-12M215 123l59-68 8 107-55-12" fill="${d.color}" stroke="#253c4c" stroke-width="5"/><path d="M229 193q49 13 56-32-5 67-78 65" fill="${d.color}" stroke="#253c4c" stroke-width="5"/><ellipse cx="151" cy="179" rx="73" ry="68" fill="${d.color}" stroke="#253c4c" stroke-width="5"/><ellipse cx="151" cy="195" rx="39" ry="43" fill="${d.horn}"/><path d="m96 74-8-48 31 31m65 0 30-31-8 48" fill="${d.horn}" stroke="#253c4c" stroke-width="5"/><rect x="83" y="56" width="137" height="111" rx="51" fill="${d.color}" stroke="#253c4c" stroke-width="5"/><ellipse cx="124" cy="101" rx="12" ry="16" fill="white"/><ellipse cx="179" cy="101" rx="12" ry="16" fill="white"/><circle cx="127" cy="105" r="6" fill="#253c4c"/><circle cx="176" cy="105" r="6" fill="#253c4c"/><path d="M126 133q25 22 50 0" fill="none" stroke="#253c4c" stroke-width="5" stroke-linecap="round"/><circle cx="104" cy="126" r="10" fill="#f3a5a2"/><circle cx="200" cy="126" r="10" fill="#f3a5a2"/><ellipse cx="98" cy="238" rx="30" ry="13" fill="${d.color}" stroke="#253c4c" stroke-width="5"/><ellipse cx="203" cy="238" rx="30" ry="13" fill="${d.color}" stroke="#253c4c" stroke-width="5"/>${n===3?'<path d="m117 59-5-26 25 10 14-23 15 23 24-10-5 26Z" fill="#f7c658"/>':''}</svg>`}
function heading(title,sub=''){return `<div class="toolbar">${btn(icon('arrow-left')+' Back','home','small')}<div class="eyebrow">${state.theme==='classic'?'Dragon Quest':'Princess Quest'}</div></div><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}`}
function render(){document.body.classList.toggle('princess',state.theme==='princess');let h='';
if(screen==='home')h=`<section class="hero"><div class="copy"><div class="eyebrow">Your next adventure</div><h1>Hello, ${esc(state.name)}.</h1><p>A little courage. One small step. Let’s see what you can do today.</p>${btn('Make it yours '+icon('sparkles'),'settings','small')}</div>${avatar()}</section>${state.active?`<div class="quest"><div><b>${esc(state.active.name)}</b><p>Your adventure is waiting.</p></div>${btn('Continue','resume','primary')}</div>`:''}<div class="grid"><button class="mission" data-action="find"><span class="badge">${icon('radar')}</span><h2>Find a Lost Treasure</h2><p>Follow your memories to discover where your missing treasure might be.</p><span class="arrow">Retrace my steps ${icon('arrow-right')}</span></button><button class="mission" data-action="quests"><span class="badge">${icon('swords')}</span><h2>Battle a Chore Dragon</h2><p>Turn a big chore into small challenges. Every finished step is a mighty hit.</p><span class="arrow">Choose my quest ${icon('arrow-right')}</span></button></div><div class="row" style="margin-top:24px">${btn(icon('gem')+' Dragon Den · '+state.den.length,'den','secondary')}${btn(icon('clipboard-list')+' Grown-up quest workshop','workshop','small')}</div>`;
if(screen==='quests'||screen==='workshop')h=heading(screen==='quests'?'Choose your quest':'Quest workshop','Saved quests are ready for another adventure. Make each step small and clear.')+`<div class="toolbar"><h2>Saved quests</h2>${btn(icon('plus')+' New quest','new','secondary small')}</div>`+(state.quests.length?state.quests.map((q,i)=>`<div class="quest"><div><h2>${esc(q.name)}</h2><p>${q.steps.length} small challenges</p></div><div class="row">${btn(screen==='workshop'?icon('pencil')+' Edit':'Battle '+icon('arrow-right'),screen==='workshop'?'edit':'start',screen==='workshop'?'secondary':'primary',`data-index="${i}"`)}</div></div>`).join(''):`<div class="card"><h2>Your first adventure starts here.</h2><p>Create a quest together, or adjust a template to fit your home.</p>${btn('Create my first quest','new','primary')}</div>`);
if(screen==='new')h=heading('A new adventure','Pick a starting point, then make it your own.')+`<div class="card"><h2>Make your own quest</h2><p>Any chore, anywhere. You choose the small steps.</p>${btn(icon('plus')+' Start with a blank quest','blank','primary')}</div><h2>Or start with a template</h2>`+templates.map((q,i)=>`<div class="quest"><b>${q.name}</b>${btn('Customize','template','secondary small',`data-index="${i}"`)}</div>`).join('');
if(screen==='editor')h=heading(editor.index===null?'Create a quest':'Edit your quest')+`<form id="quest-form" class="card narrow"><label for="title">Quest name</label><input id="title" required maxlength="80" value="${esc(editor.name)}" placeholder="Rescue the backyard"><label for="steps">Small challenges · one per line</label><textarea id="steps" required placeholder="Collect five toys&#10;Put the balls away">${esc(editor.steps.join('\n'))}</textarea><p class="note">A clear finish line helps. Adjust templates together. Grown-ups should help with cleaning products and unfamiliar chores.</p><label for="dragon">Your dragon</label><select id="dragon">${dragons.map((d,i)=>`<option value="${i}" ${editor.dragon===i?'selected':''}>${d.name}</option>`).join('')}</select><button class="primary" type="submit">${icon('save')} Save quest</button>${editor.index!==null?btn('Delete quest','delete','danger small'):''}</form>`;
if(screen==='find')h=`<div class="narrow">${heading('Follow your memory trail')}<div class="eyebrow">Memory ${question+1} of 6</div><div class="progress"><span style="width:${(question+1)/6*100}%"></span></div><form id="memory-form" class="card"><h2>${prompts[question]}</h2><label for="answer">${question===0?'Treasure name or description':'Your memory'}</label><input id="answer" maxlength="250" value="${esc(state.trail[question])}" ${question===0?'required':''} placeholder="${question===0?'My red shoe':'Anything you remember is helpful'}"><div class="row" style="margin-top:20px">${question>0?btn(icon('arrow-left')+' Previous','previous','secondary'):''}<button class="primary" type="submit">${question===5?'Read my trail':'Next'} ${icon('arrow-right')}</button>${question>0?btn('I’m not sure','unsure','small'):''}</div></form><p class="note">The radar is pretend. Your memories provide the clues.</p></div>`;
if(screen==='trail'){const a=state.trail;h=`<div class="narrow">${heading('Your treasure trail')}<div class="radar" aria-hidden="true"></div><div class="card trail"><p>You’re looking for <strong>${esc(a[0])}</strong>.</p>${a.slice(1).map((x,i)=>x&&x!=='Not sure'?`<p>${['You last remember having it:','You were at:','You were:','Next, you remember:','You remember about putting it down or moving it:'][i]} <strong>${esc(x)}</strong>.</p>`:'').join('')}<p>Start with the place you remember best, then follow that same path. Look carefully where you stopped or put things down.</p><div class="row">${btn(icon('check')+' Found it!','found','primary')}${btn(icon('pencil')+' Edit my memories','edit-trail','secondary')}</div></div><p>No rush. You can come back to this trail whenever you need it.</p></div>`}
if(screen==='found')h=heading('Treasure recovered!')+`<div class="card challenge">${icon('gem')}<h2>You followed your memories.</h2><p>You found ${esc(state.trail[0])}. Nice exploring!</p>${btn('Back to adventures','home','primary')}</div>`;
if(screen==='battle'||screen==='moves'){const a=state.active;if(!a){screen='quests';return render()}const percent=Math.round((a.steps.length-a.done)/a.steps.length*100);h=heading(esc(a.name))+`<div class="battle"><div class="toolbar"><b>${dragons[a.dragon].name}</b><span>${percent}% dragon energy</span></div><div class="progress"><span style="width:${percent}%"></span></div>${dragon(a.dragon)}<div class="eyebrow">Challenge ${a.done+1} of ${a.steps.length}</div></div><div class="card challenge"><h2>${esc(a.steps[a.done])}</h2>${screen==='battle'?`${btn(icon('swords')+' Done — attack!','moves','primary')}<div class="row" style="justify-content:center;margin-top:14px">${btn('Too big!','split','secondary small')}${btn('Already done','skip','small')}</div><details style="text-align:left;margin-top:24px"><summary>See my quest</summary><ol>${a.steps.map((s,i)=>`<li>${i<a.done?'✓ ':''}${esc(s)}</li>`).join('')}</ol></details>`:`<p>Choose your move. Every attack has the same power.</p><div class="attack-grid">${[['swords','Sword Slash'],['zap','Lightning Strike'],['snowflake','Ice Blast'],['hand','Power Punch']].map(([i,l],n)=>btn(icon(i)+l,'attack','secondary',`data-index="${n}"`)).join('')}</div>${btn('Back','battle','small')}`}</div>`}
if(screen==='split')h=heading('Make this step smaller')+`<form id="split-form" class="card narrow"><h2>${esc(state.active.steps[state.active.done])}</h2><label for="parts">Replace it with smaller steps · one per line</label><textarea id="parts" required placeholder="Put away five pieces&#10;Put away five more pieces"></textarea><p>Ask a grown-up for help if you need ideas.</p><button type="submit" class="primary">Save smaller steps</button>${btn('Cancel','battle','small')}</form>`;
if(screen==='victory')h=heading('Dragon defeated!')+`<div class="battle">${dragon(state.den.at(-1)?.dragon||0,'defeated')}<h2>Big quest. Small steps. You did it!</h2><p>Your dragon is now a friendly companion in your Dragon Den.</p>${btn(icon('gem')+' Visit my Dragon Den','den','primary')}${btn('Home','home','small')}</div>`;
if(screen==='den')h=heading('Your Dragon Den','Every dragon here is a reminder of a quest you finished.')+(state.den.length?`<div class="grid">${state.den.map(d=>`<div class="card challenge">${dragon(d.dragon)}<h2>${dragons[d.dragon].name}</h2><p>${esc(d.quest)}</p><span class="note">${new Date(d.date).toLocaleDateString()}</span></div>`).join('')}</div>`:`<div class="card"><p>Your first dragon is waiting to meet you. Finish a chore quest to bring it here.</p>${btn('Choose a quest','quests','primary')}</div>`);
if(screen==='settings')h=heading('Make it yours','Choose the adventure that feels like you.')+`<form id="settings-form" class="card narrow"><div style="text-align:center">${avatar()}</div><label for="name">Explorer name</label><input id="name" value="${esc(state.name)}" maxlength="30" required><label for="theme">Adventure theme</label><select id="theme"><option value="classic" ${state.theme==='classic'?'selected':''}>Dragon Quest · teal, navy & gold</option><option value="princess" ${state.theme==='princess'?'selected':''}>Princess Quest · pink, plum & gold</option></select><div class="grid">${[['skin','Skin tone',['#f2cfad','#dfab7c','#c98c60','#8a573e','#503629']],['hair','Hair color',['#473129','#b3763c','#e2bd69','#1f2430','#be719c']],['outfit','Outfit color',['#16706b','#ad477c','#567da4','#885ca8','#d77343']]].map(([id,l,opts])=>`<div><label for="${id}">${l}</label><select id="${id}">${opts.map((c,i)=>`<option value="${c}" ${state[id]===c?'selected':''}>${id==='skin'?['Light','Warm','Tan','Brown','Deep'][i]:id==='hair'?['Brown','Auburn','Blonde','Black','Pink'][i]:['Teal','Pink','Blue','Purple','Orange'][i]}</option>`).join('')}</select></div>`).join('')}<div><label for="crown">Accessory</label><select id="crown"><option value="no" ${!state.crown?'selected':''}>Explorer</option><option value="yes" ${state.crown?'selected':''}>Royal crown</option></select></div></div><button class="primary" type="submit" style="margin-top:22px">Save my explorer</button><p class="note">Quests and progress save on this device. This version does not sync between phones or accounts.</p></form>`;
$('#app').innerHTML=h;lucide.createIcons();window.scrollTo(0,0)}
function go(s){screen=s;render()}
function celebrate(){for(let i=0;i<24;i++){let el=document.createElement('span');el.className='confetti';el.textContent=['✦','★','◆'][i%3];el.style.left=Math.random()*100+'%';el.style.color=['#ec779e','#f4bd50','#69a982'][i%3];el.style.animationDelay=Math.random()*.4+'s';document.body.append(el);setTimeout(()=>el.remove(),2600)}}
async function strike(move=0){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);const art=$('.dragon');art?.classList.add('hit');let spell=document.createElement('div');spell.className='spell';spell.textContent=['⚔','ϟ','❄','✦'][move];$('.battle')?.append(spell);await new Promise(r=>setTimeout(r,700));state.active.done++;if(state.active.done>=state.active.steps.length){state.den.push({dragon:state.active.dragon,quest:state.active.name,date:Date.now()});state.active=null;save();go('victory');celebrate()}else{save();go('battle')}busy=false}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||busy)return;const a=b.dataset.action,i=Number(b.dataset.index);if(a==='find'){question=0;go('find')}else if(a==='edit-trail'){question=0;go('find')}else if(a==='previous'){state.trail[question]=$('#answer').value.trim();question--;save();render()}else if(a==='unsure'){state.trail[question]='Not sure';save();if(question<5){question++;render()}else go('trail')}else if(a==='blank'||a==='template'||a==='edit'){let q=a==='blank'?{name:'',steps:[],dragon:0}:a==='template'?templates[i]:state.quests[i];editor={...structuredClone(q),dragon:q.dragon||0,index:a==='edit'?i:null};go('editor')}else if(a==='delete'){if(confirm('Delete this saved quest?')){state.quests.splice(editor.index,1);save();go('workshop')}}else if(a==='start'){if(state.active&&!confirm('Replace your current battle? Your saved quest will remain.'))return;state.active={...structuredClone(state.quests[i]),done:0};save();go('battle')}else if(a==='resume')go('battle');else if(a==='attack')strike(i);else if(a==='skip'){go('moves');strike(3)}else if(a==='found'){go('found');celebrate()}else go(a)});
document.addEventListener('submit',e=>{e.preventDefault();const id=e.target.id;if(id==='settings-form'){for(const k of ['name','theme','skin','hair','outfit'])state[k]=$('#'+k).value.trim();state.crown=$('#crown').value==='yes';save();go('home')}if(id==='quest-form'){const steps=$('#steps').value.split('\n').map(s=>s.trim()).filter(Boolean);if(!steps.length)return toast('Add at least one small challenge.');const q={name:$('#title').value.trim(),steps,dragon:Number($('#dragon').value)};if(!q.name)return toast('Give your quest a name.');if(editor.index===null)state.quests.push(q);else state.quests[editor.index]=q;save();go('quests')}if(id==='memory-form'){state.trail[question]=$('#answer').value.trim()||'Not sure';save();if(question<5){question++;render()}else go('trail')}if(id==='split-form'){let p=$('#parts').value.split('\n').map(s=>s.trim()).filter(Boolean);if(!p.length)return toast('Add a smaller step.');state.active.steps.splice(state.active.done,1,...p);save();go('battle')}});
render();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
