const enc=new TextEncoder();
const hex=b=>Array.from(new Uint8Array(b),v=>v.toString(16).padStart(2,'0')).join('');
async function digest(t){return hex(await crypto.subtle.digest('SHA-256',enc.encode(t)))}
export async function passwordHash(password,salt){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:100000,hash:'SHA-256'},key,256))}
const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...extra}});
const cookie=(token,age=2592000)=>`cq_session=${token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${age}`;
async function session(req,db){const token=req.headers.get('Cookie')?.match(/(?:^|;\s*)cq_session=([a-f0-9]{64})(?:;|$)/)?.[1];if(!token)return null;return db.prepare('SELECT u.id,u.username FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').bind(await digest(token),Date.now()).first()}
function validState(s){if(!s||typeof s!=='object'||Array.isArray(s))return false;if(typeof s.name!=='string'||s.name.length>80)return false;if(!['classic','princess'].includes(s.theme))return false;for(const c of ['skin','hair','outfit'])if(!/^#[a-f0-9]{6}$/i.test(s[c]))return false;if(!Array.isArray(s.quests)||!Array.isArray(s.den)||!Array.isArray(s.trail))return false;const quest=q=>q&&typeof q.name==='string'&&q.name.length<=100&&Array.isArray(q.steps)&&q.steps.length>0&&q.steps.length<=200&&q.steps.every(x=>typeof x==='string'&&x.length<=1000)&&Number.isInteger(q.dragon)&&q.dragon>=0&&q.dragon<10000000;if(s.quests.length>300||!s.quests.every(quest))return false;if(s.den.length>2000||s.den.some(d=>!Number.isInteger(d.dragon)||d.dragon<0||d.dragon>=10000000||typeof d.quest!=='string'||d.quest.length>100||!Number.isFinite(d.date)))return false;if(s.active&&(!quest(s.active)||!Number.isInteger(s.active.done)||s.active.done<0||s.active.done>=s.active.steps.length))return false;return s.trail.length===6&&s.trail.every(x=>typeof x==='string'&&x.length<=1000)}
export default {async fetch(req,env){const url=new URL(req.url);if(!url.pathname.startsWith('/api/'))return env.ASSETS.fetch(req);try{if(!env.DB)return json({error:'Database setup is incomplete.'},503);if(req.method!=='GET'&&req.headers.get('Origin')!==url.origin)return json({error:'Request origin is not allowed.'},403);let body={};if(['POST','PUT'].includes(req.method)){if(!req.headers.get('Content-Type')?.startsWith('application/json'))return json({error:'JSON required.'},415);const raw=await req.text();if(enc.encode(raw).length>250000)return json({error:'Save is too large.'},413);try{body=JSON.parse(raw)}catch{return json({error:'Invalid request.'},400)}}
if(['/api/signup','/api/login'].includes(url.pathname)&&req.method==='POST'){const bucket=await digest((req.headers.get('CF-Connecting-IP')||'local')+':'+Math.floor(Date.now()/600000));await env.DB.prepare('INSERT INTO auth_limits(bucket,attempts,expires_at) VALUES(?,1,?) ON CONFLICT(bucket) DO UPDATE SET attempts=attempts+1').bind(bucket,Date.now()+600000).run();const limit=await env.DB.prepare('SELECT attempts FROM auth_limits WHERE bucket=?').bind(bucket).first();if(limit.attempts>20)return json({error:'Too many attempts. Try again in ten minutes.'},429);await env.DB.prepare('DELETE FROM auth_limits WHERE expires_at<?').bind(Date.now()).run();const username=String(body.username||'').trim().toLowerCase(),password=body.password;if(!/^[a-z0-9_-]{3,24}$/.test(username)||typeof password!=='string'||password.length<8||password.length>128)return json({error:'Use a 3–24 character username (letters, numbers, _ or -) and an 8–128 character password.'},400);let user=await env.DB.prepare('SELECT * FROM users WHERE username=?').bind(username).first();if(url.pathname==='/api/signup'){if(user)return json({error:'That username is already taken.'},409);const id=crypto.randomUUID(),salt=hex(crypto.getRandomValues(new Uint8Array(16))),hash=await passwordHash(password,salt);try{await env.DB.prepare('INSERT INTO users VALUES(?,?,?,?,?)').bind(id,username,salt,hash,Date.now()).run()}catch{return json({error:'That username is already taken.'},409)}user={id,username}}else{const actual=await passwordHash(password,user?.salt||'dummy-salt');let diff=0;const expected=user?.password_hash||'0'.repeat(64);for(let i=0;i<64;i++)diff|=actual.charCodeAt(i)^expected.charCodeAt(i);if(!user||diff)return json({error:'Username or password is incorrect.'},401)}const token=hex(crypto.getRandomValues(new Uint8Array(32)));await env.DB.batch([env.DB.prepare('DELETE FROM sessions WHERE expires_at<?').bind(Date.now()),env.DB.prepare('INSERT INTO sessions VALUES(?,?,?)').bind(await digest(token),user.id,Date.now()+2592000000)]);return json({user:{id:user.id,username:user.username}},200,{'Set-Cookie':cookie(token)})}
const user=await session(req,env.DB);if(!user)return json({error:'Please sign in.'},401);
if(url.pathname==='/api/me'&&req.method==='GET')return json({user});
if(url.pathname==='/api/logout'&&req.method==='POST'){const token=req.headers.get('Cookie')?.match(/cq_session=([a-f0-9]{64})/)?.[1];if(token)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await digest(token)).run();return json({ok:true},200,{'Set-Cookie':cookie('',0)})}
if(url.pathname==='/api/state'&&req.method==='GET'){const row=await env.DB.prepare('SELECT data,revision FROM saves WHERE user_id=?').bind(user.id).first();return json({data:row?JSON.parse(row.data):null,revision:row?.revision||0})}
if(url.pathname==='/api/state'&&req.method==='PUT'){if(!validState(body.data)||!Number.isInteger(body.revision)||body.revision<0)return json({error:'Invalid save data.'},400);await env.DB.prepare('INSERT OR IGNORE INTO saves(user_id,data,revision) VALUES(?,?,0)').bind(user.id,'null').run();const result=await env.DB.prepare('UPDATE saves SET data=?,revision=revision+1 WHERE user_id=? AND revision=?').bind(JSON.stringify(body.data),user.id,body.revision).run();if(result.meta.changes!==1)return json({error:'Another device has newer progress. Reload its save or keep this device’s changes.'},409);return json({revision:body.revision+1})}
return json({error:'Not found.'},404)}catch(e){console.error('API failure',e.message);return json({error:'Service unavailable. Check the D1 binding and migrations, then retry.'},503)}}};
